services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file: ./frontend/.env.local
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_WS_URL: http://localhost:3001
    networks:
      - web
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
